Repository soumyadip007/hacktoberfest23, pull requests merged in 2022-10, with the labels that each got.

#19 feat - Included the fin up to the app collection
  fin-up/.browserslistrc
  fin-up/.editorconfig
  fin-up/.gitignore
  fin-up/README.md
  fin-up/angular.json
  fin-up/karma.conf.js
  fin-up/package-lock.json
  fin-up/package.json
  fin-up/src/app/app-routing.module.ts
  fin-up/src/app/app.component.html
  fin-up/src/app/app.component.scss
  fin-up/src/app/app.component.spec.ts
  fin-up/src/app/app.component.ts
  fin-up/src/app/app.module.ts
  fin-up/src/assets/.gitkeep
  fin-up/src/environments/environment.prod.ts
  fin-up/src/environments/environment.ts
  fin-up/src/favicon.ico
  fin-up/src/index.html
  fin-up/src/main.ts
  fin-up/src/polyfills.ts
  fin-up/src/styles.scss
  fin-up/src/test.ts
  fin-up/tsconfig.app.json
  fin-up/tsconfig.json
  fin-up/tsconfig.spec.json
Labels: hacktoberfest

#21 chore - fixed the lint issues for the app
  animated-countdown/script.js
  good-cheap-fast/script.js
Labels: hacktoberfest

#27 3d graph project added
  3d-Graph-Project/background.jpg
  3d-Graph-Project/canvas/background.js
  3d-Graph-Project/canvas/buttons.js
  3d-Graph-Project/canvas/drawButton.js
  3d-Graph-Project/canvas/drawMenu.js
  3d-Graph-Project/canvas/drawPoints.js
  3d-Graph-Project/canvas/drawSegments.js
  3d-Graph-Project/canvas/handlers/onAddSegmentHandler.js
  3d-Graph-Project/canvas/handlers/onClickHandler.js
  3d-Graph-Project/canvas/handlers/onSetEndHandler.js
  3d-Graph-Project/canvas/handlers/onSetStartHandler.js
  3d-Graph-Project/canvas/isInside.js
  3d-Graph-Project/canvas/isMenuArea.js
  3d-Graph-Project/canvas/mouse/mousePosition.js
  3d-Graph-Project/canvas/mouse/onMouseOver.js
  3d-Graph-Project/dijkstra.js
  3d-Graph-Project/dijkstras.js
  3d-Graph-Project/export.json
  3d-Graph-Project/index.html
  3d-Graph-Project/main.js
Labels: hacktoberfest, hacktoberfest2022, project

#28 Chess game Project added
  chess/chess_board.js
  chess/index.html
  chess/pieces.png
  chess/run-sonar.bat
  chess/sonar.properties
Labels: hacktoberfest, hacktoberfest2022

#32 Drawing app
  drawing app/index.html
  drawing app/script.js
  drawing app/style.css
Labels: hacktoberfest, hacktoberfest2022

#31 Progress circle patch
  progress circle patch/bg.jpg
  progress circle patch/index.html
  progress circle patch/progress.js
  progress circle patch/victor.min.js
Labels: hacktoberfest, hacktoberfest2022
